### ISSUE TITLE
Xcode 7: "directory not found for option" warnings for /Frameworks folder

### ISSUE THREAD

**Issue by deemadden** [Quick/Quick#360]
Building projects with Quick included as a Cocoapod in the project under Xcode 7 beta 5 result in the warning:

ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'

Upon inspection, it doesn't appear as though the folder is there.  I have seen this issue in custom framework contexts, and have been able to resolve it by removing the reference from Build Settings.

**Comment by jeffh** [comment]
Hey @deemadden,

Thanks for filing this issue on Quick too. I mentioned in https://github.com/Quick/Nimble/issues/166 that this would be useful to resolve, but it didn't seem like just removing the framework include path would work flawlessly in previous Xcode versions. I could be incorrect about Xcode 7 beta 5, but TBH I haven't really tried yet.

**Comment by deemadden** [comment]
I'm on beta 5, and it still works the same way.  I saw your comments on the other one.  7 will probably be going final in less than a month, so it probably isn't a big deal to wait to make the change until then.

**Comment by taiheng** [comment]
This warning actually exists in Nimble for carthage builds, fixed in pull request quick/nimble#185

**Comment by aloifolia** [comment]
This issue still exists in my recently installed Xcode 7.0.1.
![screen shot 2015-10-05 at 17 06 00](https://cloud.githubusercontent.com/assets/1295054/10284129/bb477fee-6b82-11e5-86b7-58b6489ba6c9.png)
I am using the following dependency:
`````
pod 'Quick', :git => 'https://github.com/Quick/Quick'
````
I thought this problem was resolved. Am I mistaken?

**Comment by jeffh** [comment]
This is resolved on master of Quick, I haven't cut a release of Quick yet.

**Comment by jeffh** [comment]
v0.7.0 is out. Closing.
