### ISSUE TITLE
Quick not usable in XCode 7.1

### ISSUE THREAD

**Issue by daneov** [Quick/Quick#406]
`Include of non-modular header inside framework module 'Quick.Quick
#import <Quick/QuickSpec.h>

Error: could not build Objective-C module 'Quick'`

I receive the afforementioned error when trying to build using XCode 7.1 beta 3.

According to this [post](http://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module#answer-28552525) : it is related to the position of some includes.

I tried turning on the * Allow Non-modular includes in Frame Modules* flag, to no avail. I cannot build in XCode version 7.1 (7B91b).

Searching further.

**Comment by daneov** [comment]
Possibly related to the issue mentioned in this repo https://github.com/blindsey/Swift-TDD `Xcode-beta3 and CocoaPods don't work with "Defines Module" turned on for Nimble`

**Comment by daneov** [comment]
Confirmed by https://github.com/Quick/Quick/issues/402#issuecomment-149926226

**Comment by tomaszwojcik** [comment]
Confirmed for XCode 7.1 (7B91b).

**Comment by daneov** [comment]
Related to https://github.com/CocoaPods/CocoaPods/issues/3847#issuecomment-145929477 ?

**Comment by tomaszwojcik** [comment]
Exactly, I get the `Include of non-modular header inside framework module` error.

**Comment by daneov** [comment]
Cloned the Quick project, had the same warning.
Adding 

`#import "QCKDSL.h"
#import "QuickConfiguration.h"`

to the `QuickSpec.h` file made it disappear.

**Comment by tomaszwojcik** [comment]
Still got the same issue :/

https://github.com/tomaszwojcik/Quick/commit/0d796962d1ec0450d844d9cb28f73485cd4af7be

**Comment by daneov** [comment]
In the podifle : `pod 'Quick', :git => 'https://github.com/Quick/Quick.git' `, results in : 

Quick.build/unextended-module.modulemap:2:19: Umbrella header 'Quick-umbrella.h' not found

**Comment by nordfogel** [comment]
I can confirm this issue for Quick 0.7.0 and Nimble 2.0.0
I have changed the pod file to the new branches:

pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'xcode7.1'
pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'xcode7.1'

which fixed the issue for Nimble (change: removed imports in Nimble.h) BUT still appears for Quick based on the existing import in the
Quick bridging header Quick.h:

#import <Quick/QuickSpec.h>

**Comment by joemasilotti** [comment]
I'll chime in to note that I am experiencing the same issue. The `xcode7.1` branch doesn't seem to fix anything as I'm still seeing the "Umbrella header not found" error.

**Comment by daneov** [comment]
Changed branches as well, to no avail. (xcode7.1 is the default branch, but I changed it as well to double check).

This is a rather impeding issue..

**Comment by daneov** [comment]
Syncing cocoapods issue https://github.com/CocoaPods/CocoaPods/issues/4420#issuecomment-150555845. Author believes fixing https://github.com/CocoaPods/CocoaPods/issues/3767 might fix the problem. Seems to be an XCode - Cocoapods issue

**Comment by andreamazz** [comment]
I removed the import from the umbrella header, and it's working. Not sure if this is going to break anything else though. 
I forked the project here: https://github.com/andreamazz/Quick

**Comment by serieuxchat** [comment]
This work-around seems to work for now (add to Podfile)

post_install do |installer|
    `find Pods -regex 'Pods\\/Quick\\/Quick\\/Quick\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Quick\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

**Comment by jeffh** [comment]
I've pushed some changes for fixing Xcode 7.1 support on to the `xcode7.1` branch. Please let me know if you find any issues. I'll be cutting a new release in the next 24 hours.

I've also opened a PR for [tvOS support](https://github.com/Quick/Quick/pull/409).

**Comment by tomaszwojcik** [comment]
Still not working for me: `<project path>/Pods/Quick/Quick/Quick.h:9:9: Include of non-modular header inside framework module 'Quick.Quick'`

* CocoaPods 0.39.0
* Cleaned CocoaPods caches
* Cleaned XCode project

**Comment by zhigang1992** [comment]
Reposting @serieuxchat 's workaround with format

```ruby
post_install do |installer|
`find Pods -regex 'Pods\\/Quick\\/Quick\\/Quick\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Quick\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
```

**Comment by tomaszwojcik** [comment]
That workaround works for me. :+1:

**Comment by daneov** [comment]
This fixes the nimble error as well (replacing Quick with Nimble), but leaves me with 
![screen shot 2015-10-26 at 10 08 47](https://cloud.githubusercontent.com/assets/7900887/10725292/3b7e0928-7bcb-11e5-9e0f-ca2b408fe248.png)
Should I create a different issue ?

**Comment by daneov** [comment]
Workaround confirmed working. :+1:

**Comment by jeffh** [comment]
@tomaszwojcik: are you using the xcode7.1 branch?

**Comment by tomaszwojcik** [comment]
@jeffh Yes

**Comment by knellr** [comment]
The workaround isn't working for me when applied to the latest release or to the xcode7.1 branch... Both are giving me the "Umbrella header not found" error with CocoaPods 0.39.0. Deleted cocoapods cache, cleaned build folder, deleted derived data, ran pod install, and builds are failing.

I'll continue digging but just wanted to share that I'm still having this issue.

**Comment by jeffh** [comment]
I've cut [v0.8.0](https://github.com/Quick/Quick/releases/tag/v0.8.0) which should solve tvOS issues (except for [tvOS + UI Testing Bundles](https://github.com/Quick/Quick/issues/413)).

Thanks for actively commenting on the issue. :+1:

**Comment by daneov** [comment]
@knellr You don't have a git submodule lying around somewhere that hasn't been checked out? I've had this with Amaro, the xconfigs where actually a git submodule but weren't being checked out with git clone, resulting in errors.

**Comment by joemasilotti** [comment]
After upgrading to 0.8.0 (and Nimble 3.0.0) I am experiencing the same issue. 

> `Umbrella header 'Nimble-umbrella.h' could not be found

I've tried updating Cocoapods, clearing the cache, cleaning, and removing derived data with no luck.

**Comment by knellr** [comment]
@joemasilotti we're working around this for now by downgrading to CocoaPods 0.38.2. Only seemed to affect Quick in our experience with a fairly large number of pods installed.

**Comment by yuriferretti** [comment]
@knellr I'm also facing this issue with Xcode 7.2 and using cocoapods 0.39. Could you explain my your workaround?

**Comment by knellr** [comment]
@yuriferretti unfortunately, we gave up on CocoaPods 0.39 and reverted to 0.38.2. I know others have switched to Carthage for Quick. If I got the chance I'd create a project that reproduces this and take it to the CocoaPods community.
