### ISSUE TITLE
Umbrella header 'Quick-umbrella.h' not found.

### ISSUE THREAD

**Issue by michaelfransen** [Quick/Quick#414]
I upgraded to 0.8.0 today and I am getting the following error when I try to run my tests.

```
/Library/Developer/Xcode/DerivedData/Cartwheel-fshvdphtqjjstjgryiftmroawrle/Build/Intermediates/Pods.build/Debug-iphonesimulator/Quick.build/unextended-module.modulemap:2:19: Umbrella header 'Quick-umbrella.h' not found

```

Any ideas?

**Comment by jeffh** [comment]
Nothing that comes immediately to mind. I assume you cleared your derived data?

What version of cocoapods are you using?

**Comment by michaelfransen** [comment]
I am using 0.39.0. I actually ended up using Carthage for Quick and Nimble so I got around this issue. I wish I could have figured it out though.

**Comment by daneov** [comment]
You don't happen to have any git submodules that don't get checked out do you ? Or issues with your .xconfigs ?

**Comment by marcferna** [comment]
Any update on this? I have the same issue

**Comment by jeffh** [comment]
Do you have a sample project?

**Comment by marcferna** [comment]
Created a freshly new project and is building fine...

**Comment by marcferna** [comment]
Create a fresh new test target on my project with only `Quick` and `Nimble` pods and I get the same issue:
```
.......-ewhoisxfydugpqfzpzungrlbpnpw/Build/Intermediates/Pods.build/Debug-iphonesimulator/Quick.build/unextended-module.modulemap:2:19: error: umbrella header 'Quick-umbrella.h' not found
  umbrella header "Quick-umbrella.h"
                  ^
<unknown>:0: error: could not build Objective-C module 'Quick'
```

I use Cocoapods `0.39.0`. 
I only `use_frameworks!` for the test target. My main target doens't use `use_frameworks!`

**Comment by michaelfransen** [comment]
I don't have any updates. I went with Carthage and ditched cocoa pods for these two libraries. Like @marcferna - I also have ```use_frameworks!``` for the test project but do not for the main targets.

**Comment by knellr** [comment]
We also have use_frameworks! for our test project only. We saw this with CocoaPods 0.39.0 when building in a workspace that also had a large number of non-test, non-framework pods (we had 25). For smaller numbers we had some success but this was very hard to pin down. We went through the pods one by one and couldn't identify a specific pod that caused the problem.

We reverted to CocoaPods 0.38.2 and the issue went away for us, so we didn't dig further.

**Comment by ScottRobbins** [comment]
Has this been fixed or has the problem been identified? I keep receiving this error after I did a pod install with Xcode 7.1 and cleaned my build folder, even if I go to CocoaPods 0.38.2 (though the errors are slightly different).

**Comment by geoffmacd** [comment]
Bump, also having this issue with 0.39 with Quick

**Comment by jeffh** [comment]
Based on discussion on #428: this looks like a cocoapods issue that has been fixed on master (but not yet in a released version).

**Comment by knellr** [comment]
@jeffh I couldn't find mention of the umbrella header issue  in #428, is this the CocoaPods pull request with the fix? https://github.com/CocoaPods/CocoaPods/pull/4509

**Comment by cerupcat** [comment]
Any updates on this? I tried the master version of CocoaPods and it didn't fix this.

**Comment by paulz** [comment]
Same here, tried master version of CocoaPods with no luck.

Had to resort to https://github.com/Carthage/Carthage to install Quick

**Comment by dnkoutso** [comment]
Was hit by this today as well. Test target uses `use_frameworks!` but non-test target doesnt.

This is with 1.0.0.beta.2.

**Comment by dnkoutso** [comment]
We resolved this by adding:

```ruby
  installer.pods_project.targets.select { |t| t.name.end_with? 'ServerDouble' or t.name.end_with? 'RegExp' }.each do |t|
    t.build_configurations.each do |configuration|
      settings = t.build_settings(configuration.name)
      settings['DEFINES_MODULE'] = 'NO'
    end
  end
```
