### ISSUE TITLE
No such module 'Quick'

### ISSUE THREAD

**Issue by alouanemed** [Quick/Quick#841]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

run a simple test with Nimble and Quick of a ViewModel.I run into the error metionned below. I tried everything included in the docs.

### What did you expect to happen?

xcode to run the test

### What actually happened instead?

No such module 'Quick'
No such module 'RxJava'

### Environment

List the software versions you're using:

 - Quick: 2.0.0
 - Nimble: 8.0.0
 - Xcode Version: 10
 - Swift Version: 4.2
 
 - Cocoapods: 1.6.1

**Comment by ikesyo** [comment]
Maybe you are hitting a bug which is fixed in CocoaPods 1.7.0.beta: https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.beta.2.

> Add the `FRAMEWORK_SEARCH_PATHS` necessary to import `XCTest` when it is
linked as a weak framework.

Could you try with updating CocoaPods?

**Comment by alouanemed** [comment]
I updated pod and cleaned cache, but it seems that the same error is still there.

![image](https://user-images.githubusercontent.com/7117097/54117225-9c007b00-43f0-11e9-9c02-d3edad36b982.png)

Is it related to how the targets are set in my podfile?

abstract_target 'appName' do
<<<pods here>>>


  target 'product1'
  target 'product2'
  
  target 'appNameTests' do
      inherit! :search_paths
      pod 'Quick', '~> 2.0'  # https://github.com/Quick/Quick
      pod 'Nimble', '~> 8.0'  # https://github.com/Quick/Nimble
      #pod 'RxNimble', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxNimble
      pod 'RxAtomic', :modular_headers => true
      #pod 'RxBlocking'  # https://github.com/ReactiveX/RxSwift
  end
end

target 'appNameUITests' do
    inherit! :search_paths
end

**Comment by glennposadas** [comment]
This is solvable. I've experienced this before and I used to get lost in solving the problem after fixing it. Lol. This happens whenever I add a new spec file.

Just make sure your spec file is targeting your UT scheme in its `Target Membership`.

**Comment by ikesyo** [comment]
Closing as there is no example project or how to reproduce. I see RxSwift import error in the screenshot as well so this is not related to Quick itself.
