### ISSUE TITLE
Crash on objc_getClassList in Xcode 11 beta

### ISSUE THREAD

**Issue by 0xF0D0** [Quick/Quick#912]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

ran unit test

### What did you expect to happen?

no crash

### What actually happened instead?

objc_getClassList crashes

### Environment

List the software versions you're using:

 - Quick: *2.1.0*
 - Nimble: *8.0.2*
 - Xcode Version: *11.0 beta 5 (11M382q)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.1* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.7.4* (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

**Comment by VojtaStavik** [comment]
I can't replicate this. Can you provide an example project, please?

**Comment by clausjoergensen** [comment]
Most likely #873

**Comment by VojtaStavik** [comment]
@clausjoergensen I wasn't able to replicate it using the 2.1.0 version where this change is not merged yet. It would be great if @0xF0D0 or @bupojung could provide more information about how to replicate this.

**Comment by 0xF0D0** [comment]
@VojtaStavik sorry for the late reply. I also tried to replicate this, but it seems like it's ocurring only to certain project. Let me provide one when I replicate the same situation. Sorry for the late replay again

**Comment by achernoprudov** [comment]
I had got this issue after I moved project to multiproject architecture. But can't understand connection. 
Tried to make another workspace to multiproject architecture with Quick tests but it didn't work out.
Maybe it is objc runtime bug.

Also tried to execute in debug mode `objc_getClassList(NULL, 0);` and in first time it produces:
`error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x9).`

But next time this evaluation produces:
`
SingletonMetadataCache(0x6000018705a0): cyclic metadata dependency detected, aborting
error: Execution was interrupted, reason: signal SIGABRT.`

So I cant give sources to reproduce issue but I can provide any information that you need.

**Comment by achernoprudov** [comment]
For me problem was that `objc_getClassList(NULL, 0)` chashed even outside tests. I tried to call this method in `AppDelegate` in debug run and had same crash.
So real problem was in `RxCocoa` dependency in the dependent module. So I have just removed this dependency from module and everything works fine now.

So I think this crash is not related to `Quick`. `Quick` crash is just effect of the low level problem in objc/swift environment.

**Comment by ikesyo** [comment]
I assume this is already addressed by #873 and #901. Please try master branch.

**Comment by MihauMihau** [comment]
Unfortunately the issue is still here - I've got a crash in objc_getClassList when running unit tests. On Xcode 10.x it's ok, on 11.1 it crashed. Latest version of Quick 2.2.0.

**Comment by bupojung** [comment]
this issue is still here with xcode 11 quick 2.1.0

**Comment by VojtaStavik** [comment]
An Xcode project where this issue can be reproduced would be really appreciated.
